[project]
name = "mcp-moviepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.5",
    "moviepy[all]>=2.2.1",
]
