[project]
name = "mcp-moviepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.5",
    "moviepy>=2.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
